import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <nav className="navbar">
        <ul className="nav-list">
          <li className="nav-item">
            <Link href="/" className="nav-link">
              Home(SSG)
            </Link>
          </li>

          <li className="nav-item">
            <Link href="/news" className="nav-link">
              News(ISR)
            </Link>
          </li>
          <li className="nav-item">
            <Link href="/blogs" className="nav-link">
              Blogs(SSR)
            </Link>
          </li>
          <li className="nav-item">
            <Link href="/todolist" className="nav-link">
              TodoList(CSR)
            </Link>
          </li>
        </ul>
      </nav>
      <body>{children}</body>
    </html>
  );
}
